I added upload file and upload a new text
coezen73/MEETSKY_PROJECT_GROUP9 pull request #15
Opened 2022-03-12 12:34 UTC by BilginK

I hope it was a problem-free pull request.

2022-03-12 14:35 UTC, ibrhmucar approved these changes

2022-03-13 21:55 UTC, Umit-Sahin requested changes

2022-03-13 21:55 UTC, Umit-Sahin commented on configuration.properties
> -browser= remote_chrome
Origin should remain "remote_crome"

2022-03-13 21:55 UTC, Umit-Sahin commented on src/test/resources/features/Files.feature
> +	#{color:#de350b}*US*{color}
Line 21 and 25 could be delete

2022-03-13 21:55 UTC, Umit-Sahin commented on src/test/resources/features/Files.feature
> +#{color:#de350b}*US*{color}
Line 35 and 39 could be deleted

2022-03-13 21:55 UTC, Umit-Sahin commented on target/test-classes/features/Files.feature
>  	#{color:#ff0000}*US*{color}
Line 4,21,25 could be delete

2022-03-13 21:55 UTC, Umit-Sahin commented on src/test/java/net/meetsky/runners/SkyRunner.java
> +        tags = " @ETSKY-395"
In generally tags should remain @smoke in order to get smoke test result

2022-03-14 22:01 UTC, merged